CREATE DATABASE IF NOT EXISTS borderwatch CHARACTER SET utf8mb4;
USE borderwatch;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(256) NOT NULL,
  full_name VARCHAR(128) NOT NULL,
  role ENUM('ROLE_ADMIN','ROLE_DIRECTOR','ROLE_OFFICER','ROLE_OPS','ROLE_AUDITOR','ROLE_BEACON') NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trucks (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  truck_id VARCHAR(20) NOT NULL UNIQUE,
  plate_number VARCHAR(20) NOT NULL,
  operator_name VARCHAR(128) NOT NULL,
  operator_email VARCHAR(128) DEFAULT NULL,
  operator_phone VARCHAR(30) DEFAULT NULL,
  cargo_type ENUM('PETROLEUM','ELECTRONICS','PHARMACEUTICALS','FIREARMS','GENERAL_GOODS','FOODSTUFFS') NOT NULL DEFAULT 'GENERAL_GOODS',
  api_key_hash VARCHAR(256) DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS corridors (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  waypoints_json JSON NOT NULL,
  tolerance_km DECIMAL(5,1) NOT NULL DEFAULT 25.0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS truck_telemetry (
  id CHAR(36) NOT NULL PRIMARY KEY,
  truck_id VARCHAR(20) NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  speed_kmh DECIMAL(5,1) DEFAULT NULL,
  heading DECIMAL(5,1) DEFAULT NULL,
  timestamp DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  status ENUM('ON_ROUTE','OFF_ROUTE','STATIONARY') NOT NULL DEFAULT 'ON_ROUTE',
  corridor_id VARCHAR(64) DEFAULT NULL,
  deviation_km DECIMAL(8,2) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_truck_id (truck_id),
  INDEX idx_timestamp (timestamp DESC),
  INDEX idx_status (status)
);

CREATE TABLE IF NOT EXISTS compliance_violations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  telemetry_id CHAR(36) NOT NULL,
  truck_id VARCHAR(20) NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  deviation_km DECIMAL(8,2) NOT NULL,
  corridor_id VARCHAR(64) DEFAULT NULL,
  severity ENUM('LOW','MEDIUM','HIGH') NOT NULL,
  penalty_fcfa INT UNSIGNED NOT NULL,
  detected_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  status ENUM('PENDING','ACKNOWLEDGED','CONTESTED','RESOLVED') NOT NULL DEFAULT 'PENDING',
  acknowledged_by CHAR(36) DEFAULT NULL,
  acknowledged_at DATETIME DEFAULT NULL,
  INDEX idx_vio_truck (truck_id),
  INDEX idx_vio_severity (severity),
  INDEX idx_vio_status (status),
  INDEX idx_vio_detected (detected_at DESC)
);

CREATE TABLE IF NOT EXISTS violation_disputes (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  violation_id CHAR(36) NOT NULL,
  filed_by_truck VARCHAR(20) NOT NULL,
  reason TEXT NOT NULL,
  filed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME DEFAULT NULL,
  resolution ENUM('UPHELD','DISMISSED','REDUCED') DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_chain (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  block_index INT UNSIGNED NOT NULL UNIQUE,
  violation_id CHAR(36) NOT NULL,
  violation_hash CHAR(64) NOT NULL,
  previous_hash CHAR(64) NOT NULL,
  block_hash CHAR(64) NOT NULL,
  timestamp DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  user_id CHAR(36) DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  action VARCHAR(128) NOT NULL,
  resource VARCHAR(128) DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  details JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_al_time (created_at DESC)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  user_id CHAR(36) NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  user_id CHAR(36) NOT NULL,
  type ENUM('VIOLATION_DETECTED','DISPUTE_FILED','VIOLATION_ACKNOWLEDGED','SYSTEM_ALERT') NOT NULL,
  title VARCHAR(256) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
