[vps]
borderwatch ansible_host=13.140.132.85 ansible_user=deployer ansible_become=yes

[vps:vars]
ansible_python_interpreter=/usr/bin/python3[vps]
borderwatch ansible_host=13.140.132.85 ansible_user=deployer ansible_become=yes

[vps:vars]
ansible_python_interpreter=/usr/bin/python3
